In [1]:
import numpy as np

In [11]:
a=np.array([[1,2,3],[3,4,5]])
b=np.array([[2,3,4],[7,8,9]])

In [13]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [16]:
b

array([[2, 3, 4],
       [7, 8, 9]])

# Addition:-

In [19]:
total=a+b
total

array([[ 3,  5,  7],
       [10, 12, 14]])

# SUbtraction:-

In [22]:
sub=a-b
sub

array([[-1, -1, -1],
       [-4, -4, -4]])

# Multiplication (.dot)

In [49]:
profit=np.array([1000,400,200])
num=np.array([[2,3],[5,6],[7,5]])
mul=np.dot(profit,num)
mul

array([5400, 6400])

In [52]:
mul

array([5400, 6400])

# Inverse

In [65]:
a= np.array([[1, 2], [3, 4]])

# Inverse of A
a_in = np.linalg.inv(a)
a_in

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# TRanspose

In [68]:
f=np.array([[3,4,5],[6,7,8],[6,7,8]])
f

array([[3, 4, 5],
       [6, 7, 8],
       [6, 7, 8]])

In [72]:
t=f.transpose()
t

array([[3, 6, 6],
       [4, 7, 7],
       [5, 8, 8]])